<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'name',
            TextType::class,
            [
                'constraints' => [
                    new NotBlank(),
                    new Length(['min' => 1, 'max' => 255])
                ]
            ]
        );

        $builder->add(
            'username',
            TextType::class,
            [
                'constraints' => [
                    new NotBlank(),
                    new Length(['min' => 1, 'max' => 255]),
                ]
            ]
        );

        $builder->add(
            'email',
            TextType::class,
            [
                'constraints' => [
                    new NotBlank(),
                    new Email(),
                    new Length(['min' => 1, 'max' => 255]),
                ]
            ]
        );

        $builder->add(
            'address',
            UserAddressType::class,
            [
                'constraints' => [
                    new NotBlank()
                ]
            ]
        );

        $builder->add(
            'phone',
            TextType::class,
            [
                'constraints' => [
                    new NotBlank(),
                    new Length(['min' => 1, 'max' => 255]),
                ]
            ]
        );

        $builder->add(
            'website',
            TextType::class,
            [
                'constraints' => [
                    new Length(['min' => 1, 'max' => 255]),
                ]
            ]
        );

        $builder->add(
            'company',
            UserCompanyType::class,
            [
                'constraints' => [
                    new NotBlank()
                ]
            ]
        );

        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => User::class,
                'constraints' => [
                    new UniqueEntity(['fields' => ['username']]),
                    new UniqueEntity(['fields' => ['email']]),
                ]
            ]
        );

        parent::configureOptions($resolver);
    }
}
